profile: web-dev

settings:
  auto_update_path: true
  verify_installations: true

tools:
  - name: git
    display_name: "Git"
    version: latest
    linux:
      package_names:
        apt: git
    macos:
      brew: git
    windows:
      package_names:
        choco: git
    post_install:
      - command: git 
        args: ['-v']

  - name: node
    display_name: "Node.js"
    version: "20.x"
    linux:
      package_names:
        apt: nodejs
    macos:
      brew: node@20
    windows:
      package_names:
        choco: nodejs # for winget ->  winget: OpenJS.NodeJS.LTS 
    post_install:
      - command: node
        args: ['-v']